# ================= WATCH DIR =================
@watch:/var/www
#@watch:/home/web1/public_html
#@watch:/home/web2/public_html

# ================= FILE ======================
*.php
*.js
*.html
*.css

# ================= EXCLUDE ===================
!node_modules/
!vendor/
!storage/
!.git/

# ================= CRITICAL ==================
@critical:.env
@critical:wp-config.php
@critical:config.php
